# Generated by Django 4.0 on 2021-12-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='report/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentications.user')),
            ],
        ),
    ]
