# Generated by Django 4.0 on 2021-12-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidreport',
            name='isReportPositive',
            field=models.BooleanField(default=False),
        ),
    ]
