# Generated by Django 4.0 on 2021-12-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidInformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstatecount',
            name='stateName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covidInformation.statename'),
        ),
    ]
