# Generated by Django 4.0 on 2021-12-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidInformation', '0002_alter_covidstatecount_statename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidstatecount',
            name='id',
        ),
        migrations.AlterField(
            model_name='covidstatecount',
            name='stateName',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='covidInformation.statename'),
        ),
    ]
