# Generated by Django 4.0 on 2021-12-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidInformation', '0003_remove_covidstatecount_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationcenters',
            name='stateName',
        ),
        migrations.AddField(
            model_name='vaccinationcenters',
            name='stateName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidInformation.statename'),
        ),
    ]
