# Generated by Django 4.0 on 2021-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidInformation', '0004_remove_vaccinationcenters_statename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstatecount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
